version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: udiverso-dispatcher-nginx
    restart: always
    ports:
      - ${LOCAL_PORT}:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: udiverso-dispatcher-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udiverso-dispatcher-php
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80